### ISSUE TITLE
ERROR:  Error in python: KeyError

### ISSUE THREAD

**Issue by tinnakorn-chotnog** [rankactive/cassandra-fdw#1]
I use cassandra 3+ and PostgreSQL 9.4 
table schema in cassandra is

CREATE TABLE scm.members (
	mem_id timeuuid,
	android_token text,
	bankaccount text,
	bankname text,
	created_at timestamp,
	deleted_at timestamp,
	email text,
	email_paypal text,
	firstname text,
	ios_token text,
	lastname text,
	oid text,
	parent_id timeuuid,
	phoneno text,
	point int,
	prefix text,
	ref_mem_id int,
	refcode text,
	refcode_count int,
	status text,
	true_wal_phoneno text,
	updated_at timestamp,
	username text,
	PRIMARY KEY (mem_id)
) 

and I have create foreign table as following the **fdw_test** schema already created

CREATE FOREIGN TABLE fdw_test.members (
	mem_id uuid,
	android_token text,
	bankaccount text,
	bankname text,
	created_at timestamptz,
	deleted_at timestamptz,
	email text,
	email_paypal text,
	firstname text,
	ios_token text,
	lastname text,
	oid text,
	parent_id uuid,
	phoneno text,
	point int,
	prefix text,
	ref_mem_id int,
	refcode text,
	refcode_count int,
	status text,
	true_wal_phoneno text,
	updated_at timestamptz,
	username text
) SERVER fdw_server OPTIONS (keyspace 'scm', columnfamily 'members');

nothing error from foreign table creation.
but where I issue SQL command "select * from fdw_test.members limit 10" the system show error message:

ERROR:  Error in python: KeyError
DETAIL:  'class_name'

** No error if no data**

Is there any solution? 
Thank you.

**Comment by Sune357** [comment]
Hello, thank for your report. I just seen your issue. The problem appears when Cassandra table have a secondary index. I commited the hotfix of your problem, so you should pull repository and upgrade fdw driver using command "python setup.py install".
